var annotated_dup =
[
    [ "mnx", "namespacemnx.html", [
      [ "global", "namespacemnx_1_1global.html", [
        [ "Barline", "classmnx_1_1global_1_1Barline.html", "classmnx_1_1global_1_1Barline" ],
        [ "Ending", "classmnx_1_1global_1_1Ending.html", "classmnx_1_1global_1_1Ending" ],
        [ "Fine", "classmnx_1_1global_1_1Fine.html", "classmnx_1_1global_1_1Fine" ],
        [ "Jump", "classmnx_1_1global_1_1Jump.html", "classmnx_1_1global_1_1Jump" ],
        [ "LyricLineMetadata", "classmnx_1_1global_1_1LyricLineMetadata.html", "classmnx_1_1global_1_1LyricLineMetadata" ],
        [ "LyricsGlobal", "classmnx_1_1global_1_1LyricsGlobal.html", "classmnx_1_1global_1_1LyricsGlobal" ],
        [ "Measure", "classmnx_1_1global_1_1Measure.html", "classmnx_1_1global_1_1Measure" ],
        [ "RepeatEnd", "classmnx_1_1global_1_1RepeatEnd.html", "classmnx_1_1global_1_1RepeatEnd" ],
        [ "RepeatStart", "classmnx_1_1global_1_1RepeatStart.html", "classmnx_1_1global_1_1RepeatStart" ],
        [ "Segno", "classmnx_1_1global_1_1Segno.html", "classmnx_1_1global_1_1Segno" ],
        [ "StyleGlobal", "classmnx_1_1global_1_1StyleGlobal.html", "classmnx_1_1global_1_1StyleGlobal" ],
        [ "Tempo", "classmnx_1_1global_1_1Tempo.html", "classmnx_1_1global_1_1Tempo" ]
      ] ],
      [ "layout", "namespacemnx_1_1layout.html", [
        [ "Group", "classmnx_1_1layout_1_1Group.html", "classmnx_1_1layout_1_1Group" ],
        [ "Staff", "classmnx_1_1layout_1_1Staff.html", "classmnx_1_1layout_1_1Staff" ],
        [ "StaffSource", "classmnx_1_1layout_1_1StaffSource.html", "classmnx_1_1layout_1_1StaffSource" ]
      ] ],
      [ "part", "namespacemnx_1_1part.html", [
        [ "Beam", "classmnx_1_1part_1_1Beam.html", "classmnx_1_1part_1_1Beam" ],
        [ "BeamHook", "classmnx_1_1part_1_1BeamHook.html", "classmnx_1_1part_1_1BeamHook" ],
        [ "Clef", "classmnx_1_1part_1_1Clef.html", "classmnx_1_1part_1_1Clef" ],
        [ "Measure", "classmnx_1_1part_1_1Measure.html", "classmnx_1_1part_1_1Measure" ],
        [ "PositionedClef", "classmnx_1_1part_1_1PositionedClef.html", "classmnx_1_1part_1_1PositionedClef" ]
      ] ],
      [ "score", "namespacemnx_1_1score.html", [
        [ "LayoutChange", "classmnx_1_1score_1_1LayoutChange.html", "classmnx_1_1score_1_1LayoutChange" ],
        [ "MultimeasureRest", "classmnx_1_1score_1_1MultimeasureRest.html", "classmnx_1_1score_1_1MultimeasureRest" ],
        [ "Page", "classmnx_1_1score_1_1Page.html", "classmnx_1_1score_1_1Page" ],
        [ "System", "classmnx_1_1score_1_1System.html", "classmnx_1_1score_1_1System" ]
      ] ],
      [ "sequence", "namespacemnx_1_1sequence.html", [
        [ "Accent", "classmnx_1_1sequence_1_1Accent.html", "classmnx_1_1sequence_1_1Accent" ],
        [ "AccidentalDisplay", "classmnx_1_1sequence_1_1AccidentalDisplay.html", "classmnx_1_1sequence_1_1AccidentalDisplay" ],
        [ "AccidentalEnclosure", "classmnx_1_1sequence_1_1AccidentalEnclosure.html", "classmnx_1_1sequence_1_1AccidentalEnclosure" ],
        [ "BreathMark", "classmnx_1_1sequence_1_1BreathMark.html", "classmnx_1_1sequence_1_1BreathMark" ],
        [ "Dynamic", "classmnx_1_1sequence_1_1Dynamic.html", "classmnx_1_1sequence_1_1Dynamic" ],
        [ "Event", "classmnx_1_1sequence_1_1Event.html", "classmnx_1_1sequence_1_1Event" ],
        [ "EventLyricLine", "classmnx_1_1sequence_1_1EventLyricLine.html", "classmnx_1_1sequence_1_1EventLyricLine" ],
        [ "EventLyrics", "classmnx_1_1sequence_1_1EventLyrics.html", "classmnx_1_1sequence_1_1EventLyrics" ],
        [ "EventMarkingBase", "classmnx_1_1sequence_1_1EventMarkingBase.html", "classmnx_1_1sequence_1_1EventMarkingBase" ],
        [ "EventMarkings", "classmnx_1_1sequence_1_1EventMarkings.html", "classmnx_1_1sequence_1_1EventMarkings" ],
        [ "Grace", "classmnx_1_1sequence_1_1Grace.html", "classmnx_1_1sequence_1_1Grace" ],
        [ "Note", "classmnx_1_1sequence_1_1Note.html", "classmnx_1_1sequence_1_1Note" ],
        [ "Ottava", "classmnx_1_1sequence_1_1Ottava.html", "classmnx_1_1sequence_1_1Ottava" ],
        [ "Pitch", "classmnx_1_1sequence_1_1Pitch.html", "classmnx_1_1sequence_1_1Pitch" ],
        [ "Rest", "classmnx_1_1sequence_1_1Rest.html", "classmnx_1_1sequence_1_1Rest" ],
        [ "SingleNoteTremolo", "classmnx_1_1sequence_1_1SingleNoteTremolo.html", "classmnx_1_1sequence_1_1SingleNoteTremolo" ],
        [ "Slur", "classmnx_1_1sequence_1_1Slur.html", "classmnx_1_1sequence_1_1Slur" ],
        [ "SoftAccent", "classmnx_1_1sequence_1_1SoftAccent.html", null ],
        [ "Space", "classmnx_1_1sequence_1_1Space.html", "classmnx_1_1sequence_1_1Space" ],
        [ "Spiccato", "classmnx_1_1sequence_1_1Spiccato.html", null ],
        [ "Staccatissimo", "classmnx_1_1sequence_1_1Staccatissimo.html", null ],
        [ "Staccato", "classmnx_1_1sequence_1_1Staccato.html", null ],
        [ "Stress", "classmnx_1_1sequence_1_1Stress.html", null ],
        [ "StrongAccent", "classmnx_1_1sequence_1_1StrongAccent.html", "classmnx_1_1sequence_1_1StrongAccent" ],
        [ "Tenuto", "classmnx_1_1sequence_1_1Tenuto.html", null ],
        [ "Tie", "classmnx_1_1sequence_1_1Tie.html", "classmnx_1_1sequence_1_1Tie" ],
        [ "Tuplet", "classmnx_1_1sequence_1_1Tuplet.html", "classmnx_1_1sequence_1_1Tuplet" ],
        [ "Unstress", "classmnx_1_1sequence_1_1Unstress.html", null ]
      ] ],
      [ "Array", "classmnx_1_1Array.html", "classmnx_1_1Array" ],
      [ "ArrayElementObject", "classmnx_1_1ArrayElementObject.html", "classmnx_1_1ArrayElementObject" ],
      [ "Base", "classmnx_1_1Base.html", "classmnx_1_1Base" ],
      [ "ContentArray", "classmnx_1_1ContentArray.html", "classmnx_1_1ContentArray" ],
      [ "ContentObject", "classmnx_1_1ContentObject.html", "classmnx_1_1ContentObject" ],
      [ "Dictionary", "classmnx_1_1Dictionary.html", "classmnx_1_1Dictionary" ],
      [ "Document", "classmnx_1_1Document.html", "classmnx_1_1Document" ],
      [ "EnumStringMapping", "structmnx_1_1EnumStringMapping.html", null ],
      [ "Fraction", "classmnx_1_1Fraction.html", "classmnx_1_1Fraction" ],
      [ "Global", "classmnx_1_1Global.html", "classmnx_1_1Global" ],
      [ "KeySignature", "classmnx_1_1KeySignature.html", "classmnx_1_1KeySignature" ],
      [ "Layout", "classmnx_1_1Layout.html", "classmnx_1_1Layout" ],
      [ "MeasureRhythmicPosition", "classmnx_1_1MeasureRhythmicPosition.html", "classmnx_1_1MeasureRhythmicPosition" ],
      [ "MnxMetaData", "classmnx_1_1MnxMetaData.html", "classmnx_1_1MnxMetaData" ],
      [ "NoteValue", "classmnx_1_1NoteValue.html", "classmnx_1_1NoteValue" ],
      [ "NoteValueQuantity", "classmnx_1_1NoteValueQuantity.html", "classmnx_1_1NoteValueQuantity" ],
      [ "Object", "classmnx_1_1Object.html", "classmnx_1_1Object" ],
      [ "Part", "classmnx_1_1Part.html", "classmnx_1_1Part" ],
      [ "RhythmicPosition", "classmnx_1_1RhythmicPosition.html", "classmnx_1_1RhythmicPosition" ],
      [ "Score", "classmnx_1_1Score.html", "classmnx_1_1Score" ],
      [ "Sequence", "classmnx_1_1Sequence.html", "classmnx_1_1Sequence" ],
      [ "SimpleType", "classmnx_1_1SimpleType.html", "classmnx_1_1SimpleType" ],
      [ "TimeSignature", "classmnx_1_1TimeSignature.html", "classmnx_1_1TimeSignature" ]
    ] ]
];